
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import "./style.css"


// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const navLinks = [
  {name : "Register" , href : "/register"},
  {name : "Login" , href : "/login"},
  {name : "Forgot Password" , href : "/forget-password"}
]

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathname = usePathname();

  return (
    <html lang="en">
      <body className="__variable_5cfdac __variable_9a8899 antialiased">
        <>
        {navLinks.map((link) => {

          const isActive = pathname === link.href || (pathname.startsWith(link.href) && link.href !== "/")

          return(
            <Link className={isActive ? "font-bold mr-4" : "text-blue-500 mr-4"} href={link.href} key={link.name}>
                {link.name}
            </Link>
          )
        })}
        {children}
        </>
        </body>
    </html>
  )
}
