import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata:Metadata={
  title : {
    default : "Next.js Tutorial - Codevolution", // عنوان الموقع في ال url بيكون global علي الموقع كله
    template : "%s | Codevolution", // %s هنا لما بتروح علي صفحة تانية بيغير ال %s بأسم عنوان الصفحة اللي انت فيها
  },
  description : "Generated by Next.js",
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <header style={{backgroundColor : "lightblue" , padding : "1rem" , color :" black"}}>
          <p>Header</p>
        </header>
        {children}

        <footer style={{backgroundColor : "ghostwhite" , padding : "1rem" , color :" black"}}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
